#
# Copyright (c) 2018-2020 by Kristoffer Paulsson <kristoffer.paulsson@talenten.se>.
#
# This software is available under the terms of the MIT license. Parts are licensed under
# different terms if stated. The legal terms are attached to the LICENSE file and are
# made available on:
#
#     https://opensource.org/licenses/MIT
#
# SPDX-License-Identifier: MIT
#
# Contributors:
#     Kristoffer Paulsson - initial implementation
#

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.synced_folder "data", "/home/vagrant/data", type: "virtualbox"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get install build-essential debhelper devscripts equivs -y
    sudo apt-get install python3 python3-setuptools python3-pip python3-dev -y
    sudo apt-get install dh-virtualenv -y

    PATH=$PATH:~/home/vagrant/.local/bin
    pip3 install pip --upgrade --user
    pip3 install virtualenv --upgrade --user

    git clone https://github.com/kristoffer-paulsson/angelos.git
    cd angelos
    cp angelos-meta/src/angelos/meta/package/debian10/debian ./debian

    pip3 install -r requirements.txt --user
    pip3 install setuptools --upgrade --user
    pip3 install wheel --upgrade --user
    pip3 install -e . --user

    # (deactivate; dpkg-buildpackage -us -uc -b)
    dpkg-buildpackage -us -uc -b

    # Copy deb to data folder.

  SHELL
end