#!/bin/sh
#
# Copyright (c) 2018-2020 by Kristoffer Paulsson <kristoffer.paulsson@talenten.se>.
#
# This software is available under the terms of the MIT license. Parts are licensed under
# different terms if stated. The legal terms are attached to the LICENSE file and are
# made available on:
#
#     https://opensource.org/licenses/MIT
#
# SPDX-License-Identifier: MIT
#
# Contributors:
#     Kristoffer Paulsson - initial implementation
#

#DEBHELPER#

# rm -fR /opt/angelos/*
# rmdir /opt/angelos
# rm -fR /var/lib/angelos/*
# rmdir /var/lib/angelos
# rm -fR /var/log/angelos/*
# rmdir /var/log/angelos
# rm -fR /etc/angelos/*
# rmdir /etc/angelos