#
# Copyright (c) 2018-2020 by Kristoffer Paulsson <kristoffer.paulsson@talenten.se>.
#
# This software is available under the terms of the MIT license. Parts are licensed under
# different terms if stated. The legal terms are attached to the LICENSE file and are
# made available on:
#
#     https://opensource.org/licenses/MIT
#
# SPDX-License-Identifier: MIT
#
# Contributors:
#     Kristoffer Paulsson - initial implementation
#
"""Address fields internationalization."""
import csv
import io

generic1 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="postcode" /> <x-addr data-field="town,city,village" /> <x-addr data-field="county,state" /><br /><x-addr data-field="country" />"""
generic2 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="village,city,town,county" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country,state" />"""
generic3 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village,state" /><br /><x-addr data-field="country" />"""
generic4 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,state_district,village,suburb,county" />, <x-addr data-field="state_code,state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />"""
generic6 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="county" /><br /><x-addr data-field="country" />"""
generic7 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,village" />, <x-addr data-field="postcode" /><br /><x-addr data-field="country" />"""
generic8 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" />, <x-addr data-field="number" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village" /> <x-addr data-field="county_code,county" /><br /><x-addr data-field="country" />"""
generic9 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,state_district" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village,state" /><br /><x-addr data-field="country" />"""
generic10 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" /><br /><x-addr data-field="postcode" />"""
generic11 = """<x-addr data-field="country" /><br /><x-addr data-field="state" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb" /><br /><x-addr data-field="road" />, <x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" />"""
generic12 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" />, <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,state_district" /><br /><x-addr data-field="city,town,village" /> - <x-addr data-field="postcode" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />"""
generic13 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city,town,state_district,village,region" /> <x-addr data-field="state_code,state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />"""
generic14 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village,state_district" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />"""
generic15 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" />, <x-addr data-field="number" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village,state,county" /><br /><x-addr data-field="country" />"""
generic16 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village,county,state_district,state" /><br /><x-addr data-field="country" />"""
generic17 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,village,county,state_district,state" /><br /><x-addr data-field="country" />"""
generic18 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" />, <x-addr data-field="road" /><br /><x-addr data-field="city,town,village,suburb,city_district,neighborhood,state" /><br /><x-addr data-field="country" />"""
generic20 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />"""
generic21 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village,state" /><br /><x-addr data-field="country" />"""
generic22 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" />, <x-addr data-field="road" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village,state" /><br /><x-addr data-field="country" />"""

fallback3 = """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="county" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />"""


FORMAT = {
    "AD": generic3,
    "AE": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="state_district,state" /><br /><x-addr data-field="country" />""",
    "AF": generic21,
    "AG": generic16,
    "AI": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="postcode" /> <x-addr data-field="country" />""",
    "AL": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,state_district,village" /><br /><x-addr data-field="country" />""",
    "AM": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="state_district,state" /><br /><x-addr data-field="country" />""",
    "AO": generic7,
    "AQ": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="country,continent" />""",
    "AR": generic9,
    "AS": generic4,
    "AT": generic9,
    "AU": generic13,
    "AW": generic17,
    "AX": generic1,
    "AZ": generic3,
    "BA": generic1,
    "BB": generic16,
    "BD": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,state_district" /><br /><x-addr data-field="city,town,village" /> - <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "BE": generic1,
    "BF": generic6,
    "BG": generic9,
    "BH": generic2,
    "BI": generic17,
    "BJ": generic18,
    "BL": generic3,
    "BM": generic2,
    "BN": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" />, <x-addr data-field="road" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="county,state_district,state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "BO": generic17,
    "BQ": generic1,
    "BR": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" />, <x-addr data-field="number" /><br /><x-addr data-field="city,town,state_district,village" /> - <x-addr data-field="state_code,state" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "BS": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="county" /><br /><x-addr data-field="country" />""",
    "BT": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" />, <x-addr data-field="house" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village,state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "BV": generic1,
    "BW": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="country" />""",
    "BY": generic11,
    "BZ": generic16,
    "CA": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road,suburb" /><br /><x-addr data-field="city,town,state_district,village" />, <x-addr data-field="state_code,state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "CC": generic3,
    "CD": generic18,
    "CF": generic17,
    "CG": generic18,
    "CH": generic1,
    "CI": generic16,
    "CK": generic16,
    "CL": generic1,
    "CM": generic17,
    "CN": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="county" /><br /><x-addr data-field="postcode" /> <x-addr data-field="state_code,state,city,town,state_district,village" /><br /><x-addr data-field="country" />""",
    "CN_en": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="county" /><br /><x-addr data-field="postcode" /> <x-addr data-field="state_code,state,city,town,state_district,village" /><br /><x-addr data-field="country" />""",
    "CN_zh": """<x-addr data-field="country" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="state_code,state" /><br /><x-addr data-field="state_district,county" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" />""",
    "CO": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,state_district,village" />, <x-addr data-field="state_code,state" /><br /><x-addr data-field="country" />""",
    "CR": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="state" />, <x-addr data-field="city,town,state_district,village" />, <x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="postcode" /> <x-addr data-field="country" />""",
    "CU": generic7,
    "CV": generic1,
    "CW": generic17,
    "CX": generic3,
    "CY": generic1,
    "CZ": generic1,
    "DE": generic1,
    "DJ": generic16,
    "DK": generic1,
    "DM": generic16,
    "DO": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" />, <x-addr data-field="state" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "DZ": generic3,
    "EC": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="city,town,state_district,village" /><br /><x-addr data-field="country" />""",
    "EE": generic1,
    "EG": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "EH": generic17,
    "ER": generic17,
    "ES": generic15,
    "ET": generic1,
    "FI": generic1,
    "FJ": generic16,
    "FK": generic2,
    "FM": generic4,
    "FO": generic1,
    "FR": generic3,
    "GA": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood,village" /><br /><x-addr data-field="city,town,county,state_district,state" /><br /><x-addr data-field="country" />""",
    "GB": generic2,
    "GD": generic17,
    "GE": generic1,
    "GF": generic3,
    "GG": generic2,
    "GH": generic16,
    "GI": generic16,
    "GL": generic1,
    "GM": generic16,
    "GN": generic14,
    "GP": generic3,
    "GQ": generic17,
    "GR": generic1,
    "GS": generic2,
    "GT": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="postcode" />-<x-addr data-field="city,town,village,state" /><br /><x-addr data-field="country" />""",
    "GU": generic4,
    "GW": generic1,
    "GY": generic16,
    "HK": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="state_district" /><br /><x-addr data-field="state" />""",
    "HK_en": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="state_district" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "HK_zh": """<x-addr data-field="country" /><br /><x-addr data-field="state" /><br /><x-addr data-field="state_district" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" />""",
    "HM": generic3,
    "HN": generic1,
    "HR": generic1,
    "HT": generic1,
    "HU": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "ID": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" /> <x-addr data-field="postcode" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "IE": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="county" /><br /><x-addr data-field="country" />""",
    "IL": generic1,
    "IM": generic2,
    "IN": generic12,
    "IO": generic2,
    "IQ": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="neighborhood,city_district,suburb" /><br /><x-addr data-field="road" /><br /><x-addr data-field="city,town,state,village" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "IR": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="province,state" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "IR_en": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="province,state" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "IR_fa": """<x-addr data-field="country" /><br /><x-addr data-field="state,province" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" /><br /><x-addr data-field="postcode" />""",
    "IS": generic1,
    "IT": generic8,
    "JE": generic2,
    "JM": generic20,
    "JO": generic1,
    "JP": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" />, <x-addr data-field="state,state_district" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "JP_en": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" />, <x-addr data-field="state,state_district" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "JP_ja": """<x-addr data-field="country" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="state,state_district" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" />""",
    "KE": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,state,village" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "KG": generic11,
    "KH": generic20,
    "KI": generic17,
    "KM": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="country" />""",
    "KN": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village" />, <x-addr data-field="state,island" /><br /><x-addr data-field="country" />""",
    "KP": generic21,
    "KR": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" />, <x-addr data-field="city,town,village" />, <x-addr data-field="state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "KR_en": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" />, <x-addr data-field="city,town,village" />, <x-addr data-field="state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "KR_ko": """<x-addr data-field="country" /><br /><x-addr data-field="state" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" /><br /><x-addr data-field="postcode" />""",
    "KW": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /> <x-addr data-field="house" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village" /><br /><x-addr data-field="country" />""",
    "KY": generic2,
    "KZ": generic11,
    "LA": generic22,
    "LB": generic2,
    "LC": generic17,
    "LI": generic1,
    "LK": generic20,
    "LR": generic1,
    "LS": generic2,
    "LT": generic1,
    "LU": generic3,
    "LV": generic7,
    "LY": generic17,
    "MA": generic3,
    "MC": generic3,
    "MD": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" />, <x-addr data-field="number" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village,state" /><br /><x-addr data-field="country" />""",
    "ME": generic1,
    "MF": generic3,
    "MG": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village" /><br /><x-addr data-field="country" />""",
    "MH": generic4,
    "MK": generic1,
    "ML": generic17,
    "MM": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village,state" />, <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "MN": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="city_district" /><br /><x-addr data-field="suburb,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="country" />""",
    "MO": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,village,state_district" /><br /><x-addr data-field="country" />""",
    "MO_pt": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,village,state_district" /><br /><x-addr data-field="country" />""",
    "MO_zh": """<x-addr data-field="country" /><br /><x-addr data-field="suburb,village,state_district" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" />""",
    "MP": generic4,
    "MQ": generic3,
    "MR": generic18,
    "MS": generic16,
    "MT": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,suburb,village" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "MU": generic18,
    "MV": generic2,
    "MW": generic16,
    "MX": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,state_district,village" />, <x-addr data-field="state_code,state" /><br /><x-addr data-field="country" />""",
    "MY": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,village" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "MZ": generic15,
    "NA": generic2,
    "NC": generic3,
    "NE": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /><br /><x-addr data-field="road" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="country" />""",
    "NF": generic3,
    "NG": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village" /> <x-addr data-field="postcode" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "NI": generic21,
    "NL": generic1,
    "NO": generic1,
    "NP": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,neighborhood,city" /><br /><x-addr data-field="county,state_district,state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "NR": generic16,
    "NU": generic16,
    "NZ": generic20,
    "OM": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="city,town,state_district,village" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "PA": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="city,town,state_district,village" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "PE": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "PF": generic3,
    "PG": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village" /> <x-addr data-field="postcode" /> <x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "PH": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village,suburb,state_district" /><br /><x-addr data-field="postcode" /> <x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "PK": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="city,town,village,state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "PL": generic1,
    "PM": generic3,
    "PN": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="city,town,island" /><br /><x-addr data-field="country" />""",
    "PR": generic4,
    "PS": generic1,
    "PT": generic1,
    "PW": generic1,
    "PY": generic1,
    "QA": generic17,
    "RE": generic3,
    "RO": generic1,
    "RS": generic1,
    "RU": generic10,
    "RW": generic16,
    "SA": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" />, <x-addr data-field="village,city_district,suburb,neighborhood" /><br /><x-addr data-field="city,town,state_district" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "SB": generic17,
    "SC": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village,island" /><br /><x-addr data-field="island" /><br /><x-addr data-field="country" />""",
    "SD": generic1,
    "SE": generic1,
    "SG": generic2,
    "SH": generic2,
    "SI": generic1,
    "SJ": generic1,
    "SK": generic1,
    "SL": generic16,
    "SM": generic8,
    "SN": generic3,
    "SO": generic21,
    "SR": generic21,
    "SS": generic17,
    "ST": generic17,
    "SV": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="postcode" /> - <x-addr data-field="city,town,village" /><br /><x-addr data-field="state" /><br /><x-addr data-field="country" />""",
    "SX": generic17,
    "SY": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" />, <x-addr data-field="number" /><br /><x-addr data-field="village,city_district,neighborhood,suburb" /><br /><x-addr data-field="postcode" /> <x-addr data-field="city,town,state_district,state" /><br /><x-addr data-field="country" />""",
    "SZ": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,village,state" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "TC": generic2,
    "TD": generic21,
    "TF": generic3,
    "TG": generic18,
    "TH": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="village" /><br /><x-addr data-field="road" /><br /><x-addr data-field="neighborhood,city,town" />, <x-addr data-field="suburb,city_district,state_district" /><br /><x-addr data-field="state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "TJ": generic1,
    "TK": generic20,
    "TL": generic17,
    "TM": generic22,
    "TN": generic3,
    "TO": generic16,
    "TR": generic1,
    "TT": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,state_district" /><br /><x-addr data-field="city,town,state_district,village" />, <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "TV": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="county,state_district,state,island" /><br /><x-addr data-field="country" />""",
    "TW": generic20,
    "TW_en": generic20,
    "TW_zh": """<x-addr data-field="country" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="city_district" /><br /><x-addr data-field="suburb,city_district,neighborhood" /><br /><x-addr data-field="road" /><br /><x-addr data-field="number" /><br /><x-addr data-field="house" /><br /><x-addr data-field="attention" />""",
    "TZ": generic14,
    "UA": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" />, <x-addr data-field="number" /><br /><x-addr data-field="suburb,city_district,state_district" /><br /><x-addr data-field="city,town,village,state" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "UG": generic16,
    "UM": generic4,
    "US": generic4,
    "UY": generic1,
    "UZ": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,village" /><br /><x-addr data-field="state,state_district" /><br /><x-addr data-field="country" /><br /><x-addr data-field="postcode" />""",
    "VA": generic8,
    "VC": generic17,
    "VE": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="road" /> <x-addr data-field="number" /><br /><x-addr data-field="city,town,state_district,village" /> <x-addr data-field="postcode" />, <x-addr data-field="state_code,state" /><br /><x-addr data-field="country" />""",
    "VG": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="city,town,village" />, <x-addr data-field="island" /><br /><x-addr data-field="country" />, <x-addr data-field="postcode" />""",
    "VI": generic4,
    "VN": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" />, <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,neighborhood" />, <x-addr data-field="city,town,state_district,village" /><br /><x-addr data-field="state" /> <x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "VU": generic17,
    "WF": generic3,
    "WS": generic17,
    "YE": generic18,
    "YT": generic3,
    "ZA": """<x-addr data-field="attention" /><br /><x-addr data-field="house" /><br /><x-addr data-field="number" /> <x-addr data-field="road" /><br /><x-addr data-field="suburb,city_district,state_district" /><br /><x-addr data-field="city,town,village,state" /><br /><x-addr data-field="postcode" /><br /><x-addr data-field="country" />""",
    "ZM": generic3,
    "ZW": generic16,
}

REGEX = r"""(?P<tag><x-addr data-field="(?P<field>[\w,]*)"./>|<br />)"""
REGEX_OLD = r"""(<x-addr data-field="([(\w,]*)"./>)"""


output = io.StringIO()
writer = csv.writer(output)
for code in FORMAT:
    template = FORMAT[code]
    parts = code.split("_")
    if len(parts) > 1:
        country = parts[0]
        lang = parts[1]
    else:
        country = code
        lang = "*"
    writer.writerow([country, lang, template])

print("\"\"\"\n{}\"\"\"".format(output.getvalue()))
