#
# Copyright (c) 2018-2020 by Kristoffer Paulsson <kristoffer.paulsson@talenten.se>.
#
# This software is available under the terms of the MIT license. Parts are licensed under
# different terms if stated. The legal terms are attached to the LICENSE file and are
# made available on:
#
#     https://opensource.org/licenses/MIT
#
# SPDX-License-Identifier: MIT
#
# Contributors:
#     Kristoffer Paulsson - initial implementation
#

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"
  config.vm.synced_folder "data", "/home/vagrant/data", nsf: true
  config.vm.provision "shell", privileged: false, inline: <<-SHELL

    sudo yum check-update
    sudo yum upgrade -y
    sudo yum groupinstall "Development Tools" -y
    sudo yum install nano git python38 python38-devel rpmdevtools -y

    pip3.8 install rpmvenv --user
    pip3.8 install virtualenv --user

    git clone https://github.com/kristoffer-paulsson/angelos.git
    cd angelos

    pip3.8 install -r requirements.txt --user
    pip3.8 install setuptools --upgrade --user
    pip3.8 install wheel --upgrade --user
    pip3.8 install -e . --user

    cp angelos-meta/src/angelos/meta/package/centos8/rpmvenv.json config.json
    rpmvenv config.json

    # Copy rpm to data folder.

  SHELL
end